# our configuration for our GitHub actions
---
name: Checks

on: [push]

jobs:
  test-lin:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        users: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test" # comand that runs our unit test in cmd
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
